# Generated by Django 4.2.3 on 2023-07-16 18:20

import auth_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Chatroom Name')),
                ('chatfilepath', models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Chat filepath')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Chat Closed')),
                ('is_handled', models.BooleanField(default=False, verbose_name='Chat handled')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='SupportClientChat',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coms.chat')),
                ('support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.supportprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('coms.chat',),
        ),
        migrations.CreateModel(
            name='OrderChat',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coms.chat')),
                ('buyer_representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_user', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier.order')),
                ('supplier_representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_user', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('coms.chat',),
        ),
        migrations.CreateModel(
            name='InterUserChat',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coms.chat')),
                ('participants', models.ManyToManyField(blank=True, related_name='chat_participants', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('coms.chat',),
        ),
        migrations.CreateModel(
            name='InterClientChat',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coms.chat')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to='auth_app.clientprofile')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='auth_app.clientprofile')),
            ],
            bases=('coms.chat',),
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coms.chat')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Chatroom Name')),
                ('image', models.ImageField(blank=True, default='assets/imgs/resources/profiledefault.png', null=True, upload_to=auth_app.models.get_file_path, verbose_name='Image')),
                ('participants', models.ManyToManyField(blank=True, related_name='group_participants', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('coms.chat',),
        ),
    ]
