# Generated by Django 4.2.2 on 2023-07-01 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0001_initial'),
        ('supplier', '0012_delete_orderchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=256, unique=True, verbose_name='Chatroom Name')),
                ('chatfilepath', models.CharField(blank=True, max_length=256, null=True, verbose_name='Chat filepath')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Chat Closed')),
                ('is_handled', models.BooleanField(default=False, verbose_name='Chat handled')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
            ],
        ),
        migrations.CreateModel(
            name='InterClientChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SupportClientChat',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coms.chat')),
                ('support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.supportprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('coms.chat',),
        ),
        migrations.CreateModel(
            name='OrderChat',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coms.chat')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier.order')),
            ],
            bases=('coms.chat',),
        ),
    ]
