# Generated by Django 4.2.2 on 2023-07-04 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0001_initial'),
        ('coms', '0002_interclientchat_initiator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='roomname',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Chatroom Name'),
        ),
        migrations.AlterField(
            model_name='interclientchat',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to='auth_app.clientprofile'),
        ),
        migrations.AlterField(
            model_name='interclientchat',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='auth_app.clientprofile'),
        ),
        migrations.AlterField(
            model_name='orderchat',
            name='buyer_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderchat',
            name='supplier_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
