# Generated by Django 4.2.2 on 2023-07-05 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coms', '0003_alter_chat_roomname_alter_interclientchat_initiator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-updated_on']},
        ),
        migrations.CreateModel(
            name='InterUserChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.ManyToManyField(blank=True, null=True, related_name='chat_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
