# Generated by Django 4.2.2 on 2023-07-05 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coms', '0004_alter_chat_options_interuserchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interuserchat',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='chat_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.ManyToManyField(blank=True, related_name='group_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
