# Generated by Django 4.2.2 on 2023-07-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coms', '0006_remove_interclientchat_id_interclientchat_chat_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='interuserchat',
            name='id',
        ),
        migrations.AddField(
            model_name='groupchat',
            name='chat_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coms.chat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interuserchat',
            name='chat_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coms.chat'),
            preserve_default=False,
        ),
    ]
