# Generated by Django 4.2.2 on 2023-07-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coms', '0007_remove_groupchat_id_remove_interuserchat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Chatroom Name'),
        ),
    ]
