# Generated by Django 4.2.2 on 2023-07-05 15:40

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coms', '0008_groupchat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='image',
            field=models.ImageField(blank=True, default='assets/imgs/resources/profiledefault.png', null=True, upload_to=auth_app.models.get_file_path, verbose_name='Image'),
        ),
    ]
