# Generated by Django 4.0 on 2023-08-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ticket_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
