# Generated by Django 4.0 on 2023-08-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_ticket_resolution_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_satisfaction_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
