# Generated by Django 4.0 on 2023-08-13 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_ticket_customer_satisfaction_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='customer_satisfaction_score',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='resolution_time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='response_time',
        ),
    ]
