# Generated by Django 4.0 on 2023-03-16 05:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Reference Number')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Contract completed')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Contract accepted')),
                ('payment_made', models.BooleanField(default=False, verbose_name='Contract payment made')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='auth_app.buyer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_service', to='supplier.service')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='auth_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('name_ar', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('name_de', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('price', models.CharField(blank=True, max_length=256, null=True, verbose_name='price')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='description')),
                ('billing_frequency', models.CharField(blank=True, max_length=256, null=True, verbose_name='billing_frequency')),
                ('currency_iso_code', models.CharField(blank=True, max_length=256, null=True, verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_de', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModeOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_de', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('transaction_count', models.IntegerField(default=0, verbose_name='Number of transactions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=20, verbose_name='Payment Method')),
                ('plan_id', models.CharField(max_length=30, verbose_name='Plan Id')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_de', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('features', models.ManyToManyField(related_name='features_list', to='payment.Feature')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.membershipgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Plan expiry date')),
                ('duration', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually')], max_length=256, verbose_name='Duration')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='payment.feature')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ContractReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('payment_id', models.CharField(max_length=256, verbose_name='Payment Id')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount Paid')),
                ('currency', models.CharField(max_length=6, verbose_name='Currency')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.contract')),
                ('mode_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.modeofpayment')),
            ],
        ),
    ]
