# Generated by Django 4.0 on 2023-03-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='duration',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Duration'),
        ),
    ]
