# Generated by Django 4.1.7 on 2023-03-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipgroup',
            name='group_type',
        ),
        migrations.AlterField(
            model_name='feature',
            name='paypal_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='paypal_id'),
        ),
    ]
