# Generated by Django 4.0 on 2023-03-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='membership',
            field=models.ManyToManyField(related_name='features', to='payment.MembershipPlan'),
        ),
    ]
