# Generated by Django 4.0.6 on 2022-08-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="is_accepted",
            field=models.BooleanField(default=False, verbose_name="Contract accepted"),
        ),
    ]
