# Generated by Django 4.0 on 2023-03-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_feature_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipgroup',
            name='group_type',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Type'),
        ),
    ]
