# Generated by Django 4.0 on 2023-05-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_membershipgroup_group_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='features',
            field=models.ManyToManyField(related_name='features_list', to='payment.Feature'),
        ),
    ]
