# Generated by Django 4.0 on 2023-03-16 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('payment', '0003_membershipgroup_group_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='modeofpayment',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='modeofpayment',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='modeofpayment',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='modeofpayment',
            name='name_fr',
        ),
        migrations.AddField(
            model_name='membership',
            name='billing_period_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='billing_period_end_date'),
        ),
        migrations.AddField(
            model_name='membership',
            name='billing_period_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='billing_period_start_date'),
        ),
        migrations.AddField(
            model_name='membership',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.supplier'),
        ),
        migrations.AddField(
            model_name='membership',
            name='current_billing_cycle',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='current_billing_cycle'),
        ),
        migrations.AddField(
            model_name='membership',
            name='days_past_due',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='days_past_due'),
        ),
        migrations.AddField(
            model_name='membership',
            name='next_billing_date',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='next_billing_date'),
        ),
        migrations.AddField(
            model_name='membership',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='membership',
            name='payment_method_token',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='payment_method_token'),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='payment.feature'),
        ),
        migrations.AlterField(
            model_name='membershipgroup',
            name='group_type',
            field=models.CharField(blank=True, choices=[('SHOWROOMS', 'SHOWROOMS'), ('LOCAL', 'LOCAL')], max_length=256, null=True, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_token', models.CharField(max_length=256, verbose_name='card_token')),
                ('card_last_4', models.CharField(max_length=256, verbose_name='card_last_4')),
                ('card_type', models.CharField(max_length=256, verbose_name='card_type')),
                ('card_expiration_month', models.CharField(max_length=256, verbose_name='card_expiration_month')),
                ('card_expiration_year', models.CharField(max_length=256, verbose_name='card_expiration_year')),
                ('card_customer_location', models.CharField(max_length=256, verbose_name='card_customer_location')),
                ('card_issuing_bank', models.CharField(max_length=256, verbose_name='card_issuing_bank')),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.membership')),
            ],
        ),
    ]
