# Generated by Django 4.0.6 on 2022-08-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_membershipplanfeature"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MembershipPlanFeature",
            new_name="Features",
        ),
    ]
