# Generated by Django 4.0 on 2023-03-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_membership_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='current_billing_cycle'),
        ),
    ]
