# Generated by Django 4.0 on 2023-06-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_feature_price_ar_remove_feature_price_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='price_ar',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='feature',
            name='price_de',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='feature',
            name='price_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='feature',
            name='price_fr',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='price'),
        ),
    ]
