# Generated by Django 4.0.6 on 2022-08-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_alter_features_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipplan",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Price"
            ),
        ),
    ]
