# Generated by Django 4.0 on 2023-03-19 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('payment', '0005_membership_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Product Id')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('ProductType', models.CharField(default='Service', max_length=256, verbose_name='Type')),
                ('description', models.TextField(max_length=256, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='feature',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='billing_period_end_date',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='billing_period_start_date',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='client',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='current_billing_cycle',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='days_past_due',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='next_billing_date',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='payment_method_token',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='feature',
            name='has_trial',
            field=models.BooleanField(default=False, verbose_name='Has Trial Period'),
        ),
        migrations.AddField(
            model_name='feature',
            name='interval_unit',
            field=models.CharField(default=1, max_length=256, verbose_name='Duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='status',
            field=models.CharField(default=1, max_length=256, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='trial_period',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Trial Period'),
        ),
        migrations.AddField(
            model_name='feature',
            name='trial_period_count',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Trial Period Count'),
        ),
        migrations.AddField(
            model_name='membership',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Subscription Expiry Date'),
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('BRAINTREE CARD', 'BRAINTREE CARD'), ('PAYPAL', 'PAYPAL')], max_length=256, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='membership',
            name='payment_completed',
            field=models.BooleanField(default=False, verbose_name='Payment Completed'),
        ),
        migrations.AddField(
            model_name='membership',
            name='previous_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_pricing', to='payment.feature'),
        ),
        migrations.AddField(
            model_name='membership',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Subscription Start Date'),
        ),
        migrations.AddField(
            model_name='membership',
            name='upgrading_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrading_to', to='payment.feature'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.CreateModel(
            name='PaypalSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Amount Paid')),
                ('email', models.CharField(blank=True, max_length=256, null=True, verbose_name="Client's Email")),
                ('country_code', models.CharField(blank=True, max_length=9, null=True, verbose_name="Client's Country")),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name="Client's Address")),
                ('order_key', models.CharField(blank=True, max_length=256, null=True, verbose_name='Order key')),
                ('created_on', models.DateField(default=datetime.date.today, verbose_name='Created on')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paypal_membership', to='payment.membership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PaypalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Paypal ID')),
                ('name', models.CharField(max_length=256, verbose_name='Plan Name')),
                ('status', models.CharField(default='ACTIVE', max_length=256, verbose_name='Plan status')),
                ('currency', models.CharField(max_length=256, verbose_name='Plan Currency')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Plan Cost')),
                ('description', models.TextField(max_length=256, verbose_name='Description')),
                ('interval_unit', models.CharField(max_length=256, verbose_name='Plan Duration')),
                ('interval_count', models.IntegerField(default=1, verbose_name='Interval Count')),
                ('subscribers', models.IntegerField(default=0, verbose_name='Plan Subscribers')),
                ('has_trial', models.BooleanField(default=False, verbose_name='Has Trial Period')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paypalproduct')),
            ],
        ),
        migrations.CreateModel(
            name='BraintreeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='current_billing_cycle')),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True, verbose_name='Payment Method')),
                ('current_billing_cycle', models.CharField(blank=True, max_length=256, null=True, verbose_name='current_billing_cycle')),
                ('days_past_due', models.CharField(blank=True, max_length=256, null=True, verbose_name='days_past_due')),
                ('next_billing_date', models.CharField(blank=True, max_length=256, null=True, verbose_name='next_billing_date')),
                ('payment_method_token', models.CharField(blank=True, max_length=256, null=True, verbose_name='payment_method_token')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.supplier')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='braintree_membership', to='payment.membership')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
