# Generated by Django 4.0 on 2023-03-19 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('payment', '0006_paypalproduct_remove_feature_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='braintreesubscription',
            name='client',
        ),
        migrations.RemoveField(
            model_name='paypalsubscription',
            name='user',
        ),
        migrations.AddField(
            model_name='membership',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.supplier'),
        ),
        migrations.DeleteModel(
            name='PaypalPlan',
        ),
    ]
