# Generated by Django 4.0 on 2023-03-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_braintreesubscription_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpayment',
            name='membership',
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='subscription',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment.braintreesubscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='braintreesubscription',
            name='membership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='braintree_membership', to='payment.membership'),
        ),
        migrations.AlterField(
            model_name='paypalsubscription',
            name='membership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paypal_membership', to='payment.membership'),
        ),
    ]
