# Generated by Django 4.0 on 2023-03-19 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_cardpayment_membership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalsubscription',
            name='address',
        ),
        migrations.RemoveField(
            model_name='paypalsubscription',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='paypalsubscription',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paypalsubscription',
            name='total_amount_paid',
        ),
        migrations.AddField(
            model_name='feature',
            name='paypal_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Trial Period'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
    ]
