# Generated by Django 4.0.6 on 2022-08-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0009_features_name_ar_features_name_en_features_name_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="features",
            name="name_de",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="currency_de",
            field=models.CharField(max_length=6, null=True, verbose_name="Currency"),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="description_de",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="name_de",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="price_de",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, null=True, verbose_name="Price"
            ),
        ),
        migrations.AddField(
            model_name="modeofpayment",
            name="name_de",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
    ]
