# Generated by Django 4.0.6 on 2022-07-29 20:12

import auth_app.models
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth_app.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("SUPPORT", "Support"),
                    ("SUPPLIER", "Supplier"),
                    ("BUYER", "Buyer"),
                ],
                default="ADMIN",
                max_length=50,
                verbose_name="Account Type",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=auth_app.models.get_file_path,
                verbose_name="Image",
            ),
        ),
    ]
