# Generated by Django 4.0.6 on 2022-08-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_clientprofile_business_name_clientprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='business_description',
            field=models.TextField(blank=True, null=True, verbose_name='Business Description'),
        ),
    ]
