# Generated by Django 4.0.6 on 2022-07-29 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_supplier_user_account_type_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("SUPPORT", "Support"),
                    ("SUPPLIER", "Supplier"),
                    ("BUYER", "Buyer"),
                ],
                max_length=50,
                verbose_name="Account Type",
            ),
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=256, verbose_name="Country")),
                (
                    "country_code",
                    models.IntegerField(max_length=4, verbose_name="Country Code"),
                ),
                ("city", models.CharField(max_length=256, verbose_name="City")),
                ("mobile_user", models.CharField(max_length=12, verbose_name="Number")),
                (
                    "vat_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="VAT Number"
                    ),
                ),
                (
                    "legal_etity_identifier",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Legal Entity Identifier",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
