# Generated by Django 4.0.6 on 2022-08-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0004_alter_clientprofile_business_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientprofile",
            name="business_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Business Description"
            ),
        ),
    ]
