# Generated by Django 4.0 on 2023-08-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_email_activated',
            field=models.BooleanField(default=True, verbose_name='Email Activated'),
        ),
    ]
