# Generated by Django 4.0.6 on 2022-08-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_clientprofile_mobile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VAT Number'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='website',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Website'),
        ),
    ]
