# Generated by Django 4.0.6 on 2022-08-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0005_alter_clientprofile_business_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientprofile",
            name="business_name",
            field=models.CharField(max_length=256, verbose_name="Business Name"),
        ),
    ]
