# Generated by Django 4.0.6 on 2022-08-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0005_alter_clientprofile_vat_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientprofile",
            name="vat_number",
            field=models.IntegerField(blank=True, null=True, verbose_name="VAT Number"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Website"),
        ),
    ]
