# Generated by Django 4.0.6 on 2022-08-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0006_alter_clientprofile_business_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientprofile",
            name="business_description",
            field=models.TextField(default="mopm", verbose_name="Business Description"),
        ),
    ]
