# Generated by Django 4.0.6 on 2022-08-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0006_alter_clientprofile_vat_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientprofile",
            name="vat_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="VAT Number"
            ),
        ),
    ]
