# Generated by Django 4.0.6 on 2022-08-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0007_alter_clientprofile_business_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientprofile",
            name="business_description",
            field=models.TextField(verbose_name="Business Description"),
        ),
    ]
