# Generated by Django 4.0.6 on 2022-08-24 04:24

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0008_alter_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="business_description_ar",
            field=models.TextField(null=True, verbose_name="Business Description"),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="business_description_en",
            field=models.TextField(null=True, verbose_name="Business Description"),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="business_description_fr",
            field=models.TextField(null=True, verbose_name="Business Description"),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="business_name_ar",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Business Name"
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="business_name_en",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Business Name"
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="business_name_fr",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Business Name"
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="city_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="city_en",
            field=models.CharField(max_length=256, null=True, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="city_fr",
            field=models.CharField(max_length=256, null=True, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="country_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="Country"),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="country_code_ar",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Country Code"
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="country_code_en",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Country Code"
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="country_code_fr",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Country Code"
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="country_en",
            field=models.CharField(max_length=256, null=True, verbose_name="Country"),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="country_fr",
            field=models.CharField(max_length=256, null=True, verbose_name="Country"),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="mobile_user_ar",
            field=models.CharField(max_length=20, null=True, verbose_name="Number"),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="mobile_user_en",
            field=models.CharField(max_length=20, null=True, verbose_name="Number"),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="mobile_user_fr",
            field=models.CharField(max_length=20, null=True, verbose_name="Number"),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name_ar",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name_en",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name_fr",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name_ar",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name_en",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name_fr",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username_ar",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                null=True,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username_en",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                null=True,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username_fr",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                null=True,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
