# Generated by Django 4.2.2 on 2023-06-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_remove_wishlist_is_handled_remove_wishlist_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
