# Generated by Django 4.0.6 on 2022-07-31 09:33

from django.db import migrations, models
import supplier.models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default='test/django.png', upload_to=supplier.models.get_file_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(default='test/django.png', upload_to=supplier.models.get_file_path, verbose_name='Service Image'),
        ),
    ]
