# Generated by Django 4.2.2 on 2023-06-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_remove_wishlist_is_handled_remove_wishlist_product_and_more'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductvariation',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyer.cart'),
        ),
        migrations.AlterField(
            model_name='orderproductvariation',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.order'),
        ),
        migrations.CreateModel(
            name='WishListProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.product')),
            ],
        ),
    ]
