# Generated by Django 4.0.6 on 2022-07-30 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_buyer_support_alter_clientprofile_country_code_and_more'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.supplier'),
        ),
        migrations.AlterField(
            model_name='store',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.supplier'),
        ),
    ]
