# Generated by Django 4.1.2 on 2022-11-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advert",
            options={"default_manager_name": "objects"},
        ),
    ]
