# Generated by Django 4.0.6 on 2022-08-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0002_alter_productcategory_image_producttag"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency_ar",
            field=models.CharField(max_length=6, null=True, verbose_name="Currency"),
        ),
        migrations.AddField(
            model_name="product",
            name="currency_en",
            field=models.CharField(max_length=6, null=True, verbose_name="Currency"),
        ),
        migrations.AddField(
            model_name="product",
            name="currency_fr",
            field=models.CharField(max_length=6, null=True, verbose_name="Currency"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ar",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_fr",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_fr",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="product",
            name="price_ar",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, null=True, verbose_name="Price"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_en",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, null=True, verbose_name="Price"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_fr",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, null=True, verbose_name="Price"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="name_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="name_en",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="name_fr",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="name_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="name_en",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="name_fr",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="producttag",
            name="name_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="producttag",
            name="name_en",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="producttag",
            name="name_fr",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="service",
            name="currency_ar",
            field=models.CharField(max_length=6, null=True, verbose_name="Currency"),
        ),
        migrations.AddField(
            model_name="service",
            name="currency_en",
            field=models.CharField(max_length=6, null=True, verbose_name="Currency"),
        ),
        migrations.AddField(
            model_name="service",
            name="currency_fr",
            field=models.CharField(max_length=6, null=True, verbose_name="Currency"),
        ),
        migrations.AddField(
            model_name="service",
            name="description_ar",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="service",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="service",
            name="description_fr",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="service",
            name="name_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="service",
            name="name_en",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="service",
            name="name_fr",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="service",
            name="price_ar",
            field=models.DecimalField(
                decimal_places=2, max_digits=122, null=True, verbose_name="Price"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="price_en",
            field=models.DecimalField(
                decimal_places=2, max_digits=122, null=True, verbose_name="Price"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="price_fr",
            field=models.DecimalField(
                decimal_places=2, max_digits=122, null=True, verbose_name="Price"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="name_ar",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Store Name"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="name_en",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Store Name"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="name_fr",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Store Name"
            ),
        ),
    ]
