# Generated by Django 4.1.7 on 2023-03-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_store_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
    ]
