# Generated by Django 4.2.2 on 2023-06-26 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('supplier', '0002_orderproductvariation_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistproduct',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_app.clientprofile'),
            preserve_default=False,
        ),
    ]
