# Generated by Django 4.0.6 on 2022-08-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0003_product_currency_ar_product_currency_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency_de",
            field=models.CharField(max_length=6, null=True, verbose_name="Currency"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_de",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_de",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="product",
            name="price_de",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, null=True, verbose_name="Price"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="name_de",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="name_de",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="producttag",
            name="name_de",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="service",
            name="currency_de",
            field=models.CharField(max_length=6, null=True, verbose_name="Currency"),
        ),
        migrations.AddField(
            model_name="service",
            name="description_de",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="service",
            name="name_de",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="service",
            name="price_de",
            field=models.DecimalField(
                decimal_places=2, max_digits=122, null=True, verbose_name="Price"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="name_de",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Store Name"
            ),
        ),
    ]
