# Generated by Django 4.0 on 2023-03-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_store_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ManyToManyField(related_name='store_product', to='supplier.Store'),
        ),
    ]
