# Generated by Django 4.2.2 on 2023-06-26 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_wishlistproduct_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='orderproductvariation',
            name='currency',
        ),
        migrations.AlterField(
            model_name='orderproductvariation',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.productcolor'),
        ),
        migrations.AlterField(
            model_name='orderproductvariation',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.productmaterial'),
        ),
        migrations.AlterField(
            model_name='orderproductvariation',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.productprice'),
        ),
        migrations.AlterField(
            model_name='orderproductvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.product'),
        ),
    ]
