# Generated by Django 4.2.2 on 2023-06-24 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('supplier', '0003_productcolor_name_ar_productcolor_name_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Tax as a Percentage')),
                ('tax_ar', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Tax as a Percentage')),
                ('tax_fr', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Tax as a Percentage')),
                ('tax_de', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Tax as a Percentage')),
                ('tax_en', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Tax as a Percentage')),
                ('delivery_period', models.IntegerField(blank=True, null=True, verbose_name='Days of Delivery')),
                ('delivery_period_ar', models.IntegerField(blank=True, null=True, verbose_name='Days of Delivery')),
                ('delivery_period_fr', models.IntegerField(blank=True, null=True, verbose_name='Days of Delivery')),
                ('delivery_period_de', models.IntegerField(blank=True, null=True, verbose_name='Days of Delivery')),
                ('delivery_period_en', models.IntegerField(blank=True, null=True, verbose_name='Days of Delivery')),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id', '-updated_on')},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_data',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='business',
        ),
        migrations.AddField(
            model_name='order',
            name='agreed_price_ar',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Agreed Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='agreed_price_de',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Agreed Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='agreed_price_en',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Agreed Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='agreed_price_fr',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Agreed Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='auth_app.clientprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Discount as a Percentage'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_ar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Discount as a Percentage'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_de',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Discount as a Percentage'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_en',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Discount as a Percentage'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_fr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Discount as a Percentage'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Order Id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='paid_price_ar',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Paid Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_price_de',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Paid Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_price_en',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Paid Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_price_fr',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Paid Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_ar',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('VIEWED BY SUPPLER', 'VIEWED BY SUPPLER'), ('ACCEPTED BY SUPPLER', 'ACCEPTED BY SUPPLER'), ('IN DELIVERY', 'IN DELIVERY'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=256, null=True, verbose_name='Order Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_de',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('VIEWED BY SUPPLER', 'VIEWED BY SUPPLER'), ('ACCEPTED BY SUPPLER', 'ACCEPTED BY SUPPLER'), ('IN DELIVERY', 'IN DELIVERY'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=256, null=True, verbose_name='Order Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_en',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('VIEWED BY SUPPLER', 'VIEWED BY SUPPLER'), ('ACCEPTED BY SUPPLER', 'ACCEPTED BY SUPPLER'), ('IN DELIVERY', 'IN DELIVERY'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=256, null=True, verbose_name='Order Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_fr',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('VIEWED BY SUPPLER', 'VIEWED BY SUPPLER'), ('ACCEPTED BY SUPPLER', 'ACCEPTED BY SUPPLER'), ('IN DELIVERY', 'IN DELIVERY'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=256, null=True, verbose_name='Order Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='auth_app.clientprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price_ar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price_de',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price_en',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price_fr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated on'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Paid Price'),
        ),
        migrations.CreateModel(
            name='OrderShippingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=50, verbose_name='Shipping Address 1')),
                ('address_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shipping Address 1')),
                ('carrier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier.deliverycarrier')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Product Price')),
                ('color', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.productcolor')),
                ('material', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.productmaterial')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier.order')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('notes_ar', models.TextField(null=True, verbose_name='Notes')),
                ('notes_fr', models.TextField(null=True, verbose_name='Notes')),
                ('notes_de', models.TextField(null=True, verbose_name='Notes')),
                ('notes_en', models.TextField(null=True, verbose_name='Notes')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name=' Name')),
                ('chatfilepath', models.CharField(blank=True, max_length=256, null=True, verbose_name='Chat filepath')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Chat Closed')),
                ('is_handled', models.BooleanField(default=False, verbose_name='Chat handled')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier.order')),
            ],
        ),
    ]
