# Generated by Django 4.0 on 2023-03-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_alter_product_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advert',
        ),
    ]
