# Generated by Django 4.2.2 on 2023-06-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_deliverycarrier_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Agreed Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='agreed_price_ar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Agreed Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='agreed_price_de',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Agreed Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='agreed_price_en',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Agreed Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='agreed_price_fr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Agreed Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Order Id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Paid Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_price_ar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Paid Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_price_de',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Paid Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_price_en',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Paid Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_price_fr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Paid Price'),
        ),
    ]
