# Generated by Django 4.0 on 2023-03-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_delete_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified by Admin'),
        ),
    ]
