# Generated by Django 4.2.2 on 2023-06-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_alter_cart_buyer'),
        ('supplier', '0005_remove_orderproductvariation_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductvariation',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyer.cart'),
        ),
        migrations.AlterField(
            model_name='orderproductvariation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.order'),
        ),
    ]
