# Generated by Django 4.0 on 2023-03-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_product_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified by Admin'),
        ),
    ]
