# Generated by Django 4.2.2 on 2023-07-01 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_alter_ordershippingdetail_address_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycarrier',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='ordershippingdetail',
            name='address_1',
            field=models.CharField(default=1, max_length=50, verbose_name='Shipping Address 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordershippingdetail',
            name='carrier',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplier.deliverycarrier'),
            preserve_default=False,
        ),
    ]
