# Generated by Django 4.2.2 on 2023-07-01 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_deliverycarrier_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershippingdetail',
            name='address_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Shipping Address 1'),
        ),
        migrations.AlterField(
            model_name='ordershippingdetail',
            name='carrier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.deliverycarrier'),
        ),
    ]
