# Generated by Django 4.2.2 on 2023-07-01 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0011_alter_deliverycarrier_tax_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderChat',
        ),
    ]
