# Generated by Django 4.2.2 on 2023-06-26 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='Subject')),
                ('subject_ar', models.CharField(max_length=256, null=True, verbose_name='Subject')),
                ('subject_fr', models.CharField(max_length=256, null=True, verbose_name='Subject')),
                ('subject_de', models.CharField(max_length=256, null=True, verbose_name='Subject')),
                ('subject_en', models.CharField(max_length=256, null=True, verbose_name='Subject')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ar', models.TextField(null=True, verbose_name='Description')),
                ('description_fr', models.TextField(null=True, verbose_name='Description')),
                ('description_de', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified by Admin')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Country or City')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
            ],
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(blank=True, max_length=256, null=True, verbose_name='recipient')),
                ('subject', models.CharField(blank=True, max_length=256, null=True, verbose_name='subject')),
                ('sending_email', models.CharField(blank=True, max_length=256, null=True, verbose_name='sending email')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('reply_to', models.CharField(blank=True, max_length=256, null=True, verbose_name='reply_to')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_de', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ar', models.TextField(null=True, verbose_name='Description')),
                ('description_fr', models.TextField(null=True, verbose_name='Description')),
                ('description_de', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=256, verbose_name='Country')),
                ('city', models.CharField(max_length=256, verbose_name='City')),
                ('view', models.CharField(max_length=256, verbose_name='View')),
                ('request_method', models.CharField(max_length=256, verbose_name='Request Method')),
                ('device', models.CharField(max_length=256, verbose_name='Device')),
                ('user_os', models.CharField(max_length=256, verbose_name='User Os')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
            ],
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_de', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('image', models.ImageField(default='test/django.png', upload_to=manager.models.get_file_path, verbose_name='Image')),
                ('visits', models.IntegerField(default=0, verbose_name='Number of visits')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.location')),
                ('store', models.ManyToManyField(default=None, related_name='store', to='supplier.store')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=manager.models.get_file_path, verbose_name='Service Image')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.service')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_de', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('description_ar', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('description_fr', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('description_de', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('description_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=manager.models.get_file_path, verbose_name='Image')),
                ('type', models.CharField(choices=[('BANNER', 'BANNER'), ('PRODUCTS', 'PRODUCTS'), ('SUPPLIERS', 'SUPPLIERS'), ('BUYERS', 'BUYERS'), ('SHOWROOWS', 'SHOWROOWS')], max_length=256, verbose_name='Type')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('has_image', models.BooleanField(default=False, verbose_name='Has Banner Image')),
                ('showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.showroom')),
            ],
        ),
        migrations.CreateModel(
            name='EmailPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='subject')),
                ('subject_ar', models.CharField(max_length=256, null=True, verbose_name='subject')),
                ('subject_fr', models.CharField(max_length=256, null=True, verbose_name='subject')),
                ('subject_de', models.CharField(max_length=256, null=True, verbose_name='subject')),
                ('subject_en', models.CharField(max_length=256, null=True, verbose_name='subject')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('description_ar', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('description_fr', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('description_de', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('description_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=manager.models.get_file_path, verbose_name='Image')),
                ('target', models.CharField(choices=[('ALL USERS', 'ALL USERS'), ('SUPPLIERS', 'SUPPLIERS'), ('BUYERS', 'BUYERS'), ('SHOWROOWS', 'SHOWROOWS')], max_length=256, verbose_name='Type')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('has_image', models.BooleanField(default=False, verbose_name='Has Banner Image')),
                ('showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.showroom')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ar', models.TextField(null=True, verbose_name='Description')),
                ('description_fr', models.TextField(null=True, verbose_name='Description')),
                ('description_de', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=256, unique=True, verbose_name='Chatroom Name')),
                ('chatfilepath', models.CharField(blank=True, max_length=256, null=True, verbose_name='Chat filepath')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Chat Closed')),
                ('is_handled', models.BooleanField(default=False, verbose_name='Chat handled')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.supportprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('name_ar', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('name_de', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Advertising Price')),
                ('showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.showroom')),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=12, verbose_name='Total Amount')),
                ('payment_made', models.BooleanField(default=False, verbose_name='Contract payment made')),
                ('expired', models.BooleanField(default=False, verbose_name='Advert Expired')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.advertisinglocation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.product')),
            ],
            options={
                'default_manager_name': 'objects',
            },
        ),
    ]
