# Generated by Django 4.0 on 2023-03-11 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_alter_product_store'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Advertising Price')),
            ],
        ),
        migrations.DeleteModel(
            name='PlatformPrice',
        ),
        migrations.AlterField(
            model_name='showroom',
            name='store',
            field=models.ManyToManyField(default=None, related_name='store', to='supplier.Store'),
        ),
        migrations.AddField(
            model_name='advertisinglocation',
            name='showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.showroom'),
        ),
    ]
