# Generated by Django 4.0 on 2023-08-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_product_store'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='store',
            field=models.ManyToManyField(default=None, related_name='store', to='supplier.Store'),
        ),
    ]
