# Generated by Django 4.0.6 on 2022-07-31 14:56

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showroom",
            name="image",
            field=models.ImageField(
                default="test/django.png",
                upload_to=manager.models.get_file_path,
                verbose_name="Image",
            ),
        ),
    ]
