# Generated by Django 4.1.2 on 2022-11-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="description_ar",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="description_de",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="description_en",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="description_fr",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="name_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="promotion",
            name="name_de",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="promotion",
            name="name_en",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="promotion",
            name="name_fr",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
    ]
