# Generated by Django 4.2.2 on 2023-06-26 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalenderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('start', models.DateField(verbose_name='Start Date')),
                ('end', models.DateField(verbose_name='End Date')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='auth_app.clientprofile')),
            ],
        ),
    ]
