# Generated by Django 4.0 on 2023-03-11 11:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_delete_advert'),
        ('manager', '0002_advertisinglocation_delete_platformprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=12, verbose_name='Total Amount')),
                ('payment_made', models.BooleanField(default=False, verbose_name='Contract payment made')),
                ('expired', models.BooleanField(default=False, verbose_name='Advert Expired')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.advertisinglocation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.product')),
            ],
            options={
                'default_manager_name': 'objects',
            },
        ),
    ]
