# Generated by Django 4.0 on 2023-03-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified by Admin'),
        ),
    ]
