# Generated by Django 4.2.2 on 2023-06-26 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_calenderevent_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calenderevent',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='calenderevent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='calenderevent',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='calenderevent',
            name='start',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
    ]
