# Generated by Django 4.0.6 on 2022-08-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_discussionreply_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussionreply',
            options={},
        ),
    ]
