# Generated by Django 4.2.2 on 2023-07-01 18:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('manager', '0004_alter_calenderevent_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calenderevent',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Title')),
                ('category', models.CharField(blank=True, choices=[('ORDERS', 'ORDERS'), ('EMAILS', 'EMAILS'), ('CHATS', 'CHATS'), ('SUPPORT', 'SUPPORT'), ('INVENTORY', 'INVENTORY'), ('CALENDER', 'CALENDER')], max_length=256, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('viewed', models.BooleanField(default=False, verbose_name='Viewed')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='auth_app.clientprofile')),
            ],
        ),
    ]
