# Generated by Django 4.0.6 on 2022-08-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_alter_discussionreply_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="description_ar",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="discussion",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="discussion",
            name="description_fr",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="discussion",
            name="subject_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="Subject"),
        ),
        migrations.AddField(
            model_name="discussion",
            name="subject_en",
            field=models.CharField(max_length=256, null=True, verbose_name="Subject"),
        ),
        migrations.AddField(
            model_name="discussion",
            name="subject_fr",
            field=models.CharField(max_length=256, null=True, verbose_name="Subject"),
        ),
        migrations.AddField(
            model_name="discussionreply",
            name="description_ar",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="discussionreply",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="discussionreply",
            name="description_fr",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="service",
            name="description_ar",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="service",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="service",
            name="description_fr",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="service",
            name="name_ar",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="service",
            name="name_en",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="service",
            name="name_fr",
            field=models.CharField(max_length=256, null=True, verbose_name="Name"),
        ),
    ]
