# Generated by Django 4.2.2 on 2023-07-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_calenderevent_title_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('ORDERS', 'ORDERS'), ('EMAILS', 'EMAILS'), ('CHATS', 'CHATS'), ('SUPPORT', 'SUPPORT'), ('INVENTORY', 'INVENTORY'), ('CALENDER', 'CALENDER'), ('BIDS', 'BIDS'), ('CONTRACTS', 'CONTRACTS')], max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='Chatroom',
        ),
    ]
