# Generated by Django 4.0 on 2023-03-11 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_discussion_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(blank=True, max_length=256, null=True, verbose_name='recipient')),
                ('subject', models.CharField(blank=True, max_length=256, null=True, verbose_name='subject')),
                ('sending_email', models.CharField(blank=True, max_length=256, null=True, verbose_name='sending email')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('reply_to', models.CharField(blank=True, max_length=256, null=True, verbose_name='reply_to')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
            ],
        ),
    ]
