# Generated by Django 4.0 on 2023-03-12 18:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_sentemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='subject')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=manager.models.get_file_path, verbose_name='Image')),
                ('_type', models.CharField(choices=[('SUPPLIERS', 'SUPPLIERS'), ('BUYERS', 'BUYERS'), ('SHOWROOWS', 'SHOWROOWS')], max_length=256, verbose_name='Type')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('has_image', models.BooleanField(default=False, verbose_name='Has Banner Image')),
                ('showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.showroom')),
            ],
        ),
    ]
