# Generated by Django 4.0 on 2023-03-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_emailpromotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailpromotion',
            name='_type',
        ),
        migrations.AddField(
            model_name='emailpromotion',
            name='target',
            field=models.CharField(choices=[('ALL USERS', 'ALL USERS'), ('SUPPLIERS', 'SUPPLIERS'), ('BUYERS', 'BUYERS'), ('SHOWROOWS', 'SHOWROOWS')], default='SUPPLIER', max_length=256, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
